[build]
  command = "NODE_ENV=production pnpm run build"
  publish = "apps/booking-web-app/dist"
ignore = "git diff --name-only HEAD^ HEAD | grep -qvE '^apps/booking-web-app/' || git log -1 --pretty=%B | grep -q '\\[skip\\]'"

[dev]
  command = "pnpm run dev"
  port = 3000

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
