CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS transactions (
    id SERIAL PRIMARY KEY,
    senderemail VARCHAR(100) NOT NULL,
    receiveremail VARCHAR(100) NOT NULL,
    amount DECIMAL(10, 2) NOT NULL
);
